# Project: 电脑报废器
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = 电脑报废器_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/" -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/" -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/" -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/" -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib" -L"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3 -mwindows -static
INCS     = -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/include" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/include/c++/10.3.0" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/include/c++/10.3.0/x86_64-w64-mingw32" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/include/c++/10.3.0/backward" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/include" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"F:/Secret/Eric/信息技术/C++/软件/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = 电脑报废器.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "$(BIN)" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS) 

电脑报废器_private.res: 电脑报废器_private.rc 
	$(WINDRES) -i 电脑报废器_private.rc --input-format=rc -o 电脑报废器_private.res -O coff 

